version: 0.2

environment_variables:
    plaintext:
        S3_BUCKET: "react-mobx-app"
        BUILD_ENV: "prod"
phases:
    install:
        commands:
            - echo Installing source NPM dependencies...
            - node -v
            - npm -v
            - cd HubIns
            - npm install
    build:
        commands:
            - echo Build started on `date`
            - npm run build
            - aws s3 rm s3://${S3_BUCKET} --recursive
            - aws s3 cp dist s3://${S3_BUCKET} --recursive --acl=public-read
            - aws cloudfront create-invalidation --distribution-id EPGE5CIY77EQ1 --paths "/*"
            - echo Build completed on `date`
artifacts:
    files:
        - '**/*'
    base-directory: 'dist*'
    discard-paths: yes
